name: Generate NextJS Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # This caches your node_modules automatically

      - name: Install & Build
        run: |
          npm ci # 'ci' is faster and more reliable than 'install' in CI/CD
          npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          # This path includes everything needed to run the server
          path: |
            .next/standalone
            .next/static
            public/
